backend:
  name: github
  repo: torben-sc/nalan-shop
  branch: main
  base_url: https://github.com
  site_url: https://torben-sc.github.io/nalan-shop
  auth_endpoint: /auth/oauth # Falls du eine eigene OAuth konfiguriert hast


media_folder: "images" # Ordner für hochgeladene Bilder
public_folder: "images"

collections:
  - name: "products" # Name der Collection
    label: "Products" # Label, das in der Admin-Oberfläche angezeigt wird
    file: "products.json" # Ordner für die Produkte
    create: true
    slug: "{{slug}}" # URL-Slug des Produkts
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }
