backend:
  name: github
  repo: torben-sc/nalan-shop
  branch: main
  auth:
    client_id: Ov23liswnrBC64e679aq
    client_secret: 2576923ebbed8d3fe6a7368858bedf270c49dd4a


media_folder: "images" # Ordner für hochgeladene Bilder
public_folder: "images"

collections:
  - name: "products" # Name der Collection
    label: "Products" # Label, das im Admin-Bereich angezeigt wird
    file: "products.json" # JSON-Datei, in der alle Produkte gespeichert werden
    identifier_field: "name" # Ein eindeutiges Feld, das als Identifier verwendet wird
    format: "json" # Gibt an, dass das Format JSON ist
    create: true # Ermöglicht das Erstellen neuer Einträge
    fields: 
      - { label: "ID", name: "id", widget: "string", required: true }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number", required: true }
      - { label: "Images", name: "images", widget: "list", allow_multiple: true, field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Stock", name: "stock", widget: "number" }
      - { label: "Category", name: "category", widget: "string" }